### ISSUE TITLE
XY board connectors flipped

### ISSUE THREAD

**Issue by klinea2** [cmu-spacecraft-design-build-fly-2023/Avionics-Hardware#1]
- Jetson to XY board is on the outside of the XY board
- connector for XY board to the deployable solar panel is on the inside

- these need to be switched
![image](https://github.com/cmu-spacecraft-design-build-fly-2023/Avionics-Hardware/assets/138126731/5c2cc0b7-3160-4822-be61-eb8ec5d2dc77)

**Comment by Nischalm1996** [comment]
Will be flipped in Rev2 after electrical checks

**Comment by klinea2** [comment]
Sounds good, thanks! Send us the CAD models as soon as they are done!
